### ISSUE TITLE
Add details from Ben's talk

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/quantum-wednesday#8]
Hey @benmcdonough20! 👋

If you haven't seen, we put together this repo to collect data from our weekly Quantum Wednesday meetings, so those who cannot make it can still benefit.

You gave a very nice talk on 9/14/2022, and I'm wondering if you have the slides from your talk? If you'd be willing to share a public access link, feel free to drop it here and I can add it to the README, or if you want to open a PR, that'd be great as well. WDYT?

**Comment by benmcdonough20** [comment]
Hello Nate,

Thanks for reaching out! I would be happy to include the slides from my talk.

Here is a view link for the slides: [](https://www.dropbox.com/s/nih21i89zsf868b/SC22Presentation.pptx?dl=0)

Let me know if there is anything else I can do!

**Comment by benmcdonough20** [comment]
Hello @natestemen,

So sorry for not seeing this! I will figure out what is wrong and get back to you.

**Comment by benmcdonough20** [comment]
Actually @natestemen, I was able to view the PowerPoint without issues. Are you using PowerPoint version 2209?

It did take a long time to load though so there could be something going on with the image. Let me know what else I can do to help out.

**Comment by natestemen** [comment]
Ah yeah we'd really like for the slides to be viewable in browser. Is it possible to export the pptx as a pdf?

**Comment by benmcdonough20** [comment]
Yes absolutely! Here is the pdf. Let me know if there are still any issues viewing!

[BenMcDonough_SC22Presentation.pdf](https://github.com/unitaryfund/quantum-wednesday/files/11069464/BenMcDonough_SC22Presentation.pdf)

**Comment by natestemen** [comment]
Updated in https://github.com/unitaryfund/quantum-wednesday/commit/0fabe9a8c5bc9ed270e80c4815bd5384adae5851. Thanks Ben!
